# Default values for local-pvc-releaser.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  # Defining the name of the controller pod
  name: "local-pvc-releaser"

  # Number of replicas
  replicas: 2

  image:
    # Repository path to the controller image.
    repository: "appsflyer/local-pvc-releaser"
    # Tag of the controller image.
    tag:
    # Image pull policy for the controller image.
    pullPolicy: "Always"

  resources: {}
  # Controller resource allocation
  # limits:
  #  cpu: 500m
  #  memory: 128Mi
  # requests:
  #  cpu: 10m
  #  memory: 64Mi

  # Additional labels key-value pairs
  additionalLabels: {}

  # Enable PVC annotations selector
  pvcAnnotationSelector:
    enabled: false
    # Customize PVC annotation selector for key and value
    # customAnnotationKey: ""
    # customAnnotationValue: ""

  # Additional annotations key-value pairs
  additionalAnnotations: {}

  # Enable controller in dry-run mode
  dryRun: false

  # Define controller log level
  # logLevel: info

  # Enable zap logger with development mode with stack tracing
  loggingDevMode: false

  # Extra environment variables to be injected to the pod
  extraEnv: {}

  # Adding tolerations rules
  tolerations: []

  # Adding node affinity rules
  affinity: {}

prometheus:
  # This will create a ServiceMonitor that can be used by Prometheus-Operator to scrape the metrics.
  enabled: false
  # Expose metrics with secure/insecure way using auth-proxy (http/https)
  portType: http