name: Bug
description: Choose this option to let us know about an unexpected error, a crash, or otherwise incorrect behavior.
title: "[Bug]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for raising a bug report and for bringing that to our attention!

        Before submitting a bug report, please follow the section below for providing more information about the problem that you've encountered with.


  - type: textarea
    attributes:
      label: Description
      value: |
        **Observed Behavior**:
        
        **Expected Behavior**:
        
        **Reproduction Steps**
        
        **Versions**:
        - Controller Version: 
        - Chart Version: 
        - Chart Configuration (YAML):
        - Kubernetes Version (`kubectl version`):
        
        
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment