apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: service-account
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: local-pvc-releaser
    app.kubernetes.io/part-of: local-pvc-releaser
    app.kubernetes.io/managed-by: helm
  name: controller-manager
