{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.prometheus.enabled }}

# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service-monitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: local-pvc-releaser
    app.kubernetes.io/part-of: local-pvc-releaser
    app.kubernetes.io/managed-by: helm
    # Need to move to helm the option below to add annotations
    release: kube-prometheus-stack
  name: controller-manager-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: {{ .Values.prometheus.portType | default "https" }}
      scheme: {{ .Values.prometheus.portType | default "https" }}
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end -}}
